import { useEffect,useState,type FormEvent } from 'react'
import { Link,useParams,useSearchParams } from 'react-router-dom'
import { rpc,records,message,money,dateTime,type Row } from '../lib/api'
import { TenantImage } from '../components/TenantImage'
import { useSession } from '../app/session'
import { can } from '../config/access'
import { Empty,Field,Header,Loading,Modal,Notice } from '../components/ui'
export type Appointment={id:string;barbershop_id:string;shop_name:string;slug:string;customer_id:string;customer_name:string;customer_phone:string;professional_id:string;professional_name:string;service_id:string;service_name:string;starts_at:string;ends_at:string;status:string;price_cents:number}
type Slot={starts_at:string;professional_id:string;professional_name:string}
type CatalogData={shop:Row;services:Row[];professionals:Row[]}
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'})
const labels:Record<string,string>={scheduled:'Agendado',confirmed:'Confirmado',in_progress:'Em atendimento',completed:'Concluído',cancelled:'Cancelado',no_show:'Não compareceu'}
export function BookingForm({tenant,services,professionals,done,existing,initialService}:{tenant:string;services:Row[];professionals:Row[];done:()=>void;existing?:Appointment;initialService?:string}){
 const [service,setService]=useState(existing?.service_id??initialService??String(services.find(s=>s.is_active!==false)?.id??'')),[professional,setProfessional]=useState(''),[date,setDate]=useState(today()),[slots,setSlots]=useState<Slot[]>([]),[selected,setSelected]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false)
 useEffect(()=>{let active=true;setSelected('');setSlots([]);setNotice('');setLoading(true);if(!service){setLoading(false);return}
 rpc<Slot[]>('available_slots',{tenant,service,booking_date:date,professional:professional||null}).then(s=>{if(active)setSlots(s)}).catch(e=>{if(active)setNotice(message(e))}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}
 },[tenant,service,professional,date])
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const slot=slots.find(s=>`${s.professional_id}|${s.starts_at}`===selected);if(!slot)return;setBusy(true);const f=new FormData(e.currentTarget)
  try{await rpc('book_appointment',{tenant,service,professional:slot.professional_id,starts:slot.starts_at,customer_name:f.get('name'),customer_phone:f.get('phone'),customer:existing?.customer_id??null,existing_appointment:existing?.id??null});done()}
  catch(e){setNotice(message(e));setSelected('');setSlots(await rpc<Slot[]>('available_slots',{tenant,service,booking_date:date,professional:professional||null}).catch(()=>[]))}finally{setBusy(false)}
 }
 return <form className="form-grid" onSubmit={submit}><Field label="1. Serviço"><select value={service} onChange={e=>setService(e.target.value)} required><option value="">Escolha</option>{services.filter(s=>s.is_active!==false).map(s=><option key={String(s.id)} value={String(s.id)}>{s.name} · {money(Number(s.price_cents))} · {s.duration_minutes} min</option>)}</select></Field><Field label="2. Profissional"><select value={professional} onChange={e=>setProfessional(e.target.value)}><option value="">Qualquer profissional disponível</option>{professionals.map(p=><option value={String(p.id)} key={String(p.id)}>{p.name}</option>)}</select></Field><Field label="3. Data"><input type="date" value={date} min={today()} onChange={e=>setDate(e.target.value)} required/></Field><Field label="4. Horário disponível"><select value={selected} onChange={e=>setSelected(e.target.value)} required><option value="">{loading?'Buscando horários…':'Selecione um horário'}</option>{slots.map(s=><option value={`${s.professional_id}|${s.starts_at}`} key={`${s.professional_id}|${s.starts_at}`}>{dateTime(s.starts_at)} · {s.professional_name}</option>)}</select></Field>{!loading&&!slots.length&&<p className="full">Sem horários disponíveis nesta data. Tente outro dia ou profissional.</p>}<Field label="5. Nome do cliente"><input name="name" required minLength={2} defaultValue={existing?.customer_name}/></Field><Field label="Telefone / WhatsApp"><input name="phone" type="tel" minLength={8} maxLength={30} required defaultValue={existing?.customer_phone}/></Field><Notice text={notice}/><button className="primary full" disabled={busy||!selected}>{busy?'Reservando…':existing?'Confirmar remarcação':'Confirmar agendamento'}</button></form>
}
export function Agenda(){
 const [paymentMethods,setPaymentMethods]=useState<string[]>([])
 const session=useSession()
 const {tenant=''}=useParams(),[date,setDate]=useState(today()),[view,setView]=useState('day'),[rows,setRows]=useState<Appointment[]>([]),[catalog,setCatalog]=useState<{services:Row[];professionals:Row[]}>({services:[],professionals:[]}),[modal,setModal]=useState<Appointment|'new'|null>(null),[pay,setPay]=useState<Appointment|null>(null),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true)
 const member=session.memberships.find(m=>m.barbershop_id===tenant),manage=can(member?.role??(session.admin?'owner':null),'appointments:manage')
 const load=async()=>{try{const start=new Date(date+'T00:00:00-03:00'),end=new Date(start);end.setDate(end.getDate()+(view==='week'?7:view==='list'?30:1));setRows(await rpc<Appointment[]>('agenda',{tenant,from_date:start.toISOString(),until_date:end.toISOString()}))}catch(e){setNotice(message(e))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[tenant,date,view]) // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{void rpc<string[]>('appointment_payment_methods',{tenant}).then(setPaymentMethods).catch(e=>setNotice(message(e)));Promise.all([records('services',tenant),records('professionals',tenant)]).then(([services,professionals])=>setCatalog({services,professionals})).catch(()=>{})},[tenant])
 async function action(a:Appointment,status:string,method?:string){try{await rpc('appointment_action',{appointment:a.id,new_status:status,method:method??null});setPay(null);setNotice('Agenda atualizada.');await load()}catch(e){setNotice(message(e))}}
 return <><Header title="Agenda" subtitle="Cada horário no lugar certo.">{manage&&<button className="primary" onClick={()=>setModal('new')}>+ Novo agendamento</button>}</Header><Notice text={notice}/><div className="toolbar"><input type="date" aria-label="Data da agenda" value={date} onChange={e=>setDate(e.target.value)}/><div className="tabs">{[['day','Dia'],['week','Semana'],['list','Lista']].map(([v,l])=><button key={v} className={view===v?'selected':''} onClick={()=>setView(v!)}>{l}</button>)}</div></div>{loading?<Loading/>:!rows.length?<Empty text="Agenda livre neste período."/>:<div className="agenda-list">{rows.map(a=><article className={`appointment ${a.status}`} key={a.id}><div className="appointment-time">{dateTime(a.starts_at)}<small>{a.professional_name}</small></div><div><h3>{a.customer_name}</h3><p>{a.service_name} · {money(a.price_cents)}</p></div><span className="badge">{labels[a.status]}</span>{!['completed','cancelled','no_show'].includes(a.status)&&<div className="actions"><select aria-label={`Alterar status de ${a.customer_name}`} value="" onChange={e=>{if(e.target.value==='completed')setPay(a);else if(confirm(`Marcar como ${labels[e.target.value]}?`))void action(a,e.target.value)}}><option value="">Atualizar status</option>{['confirmed','in_progress','completed','cancelled','no_show'].map(v=><option value={v} key={v}>{labels[v]}</option>)}</select>{manage&&<button onClick={()=>setModal(a)}>Remarcar</button>}</div>}</article>)}</div>}
 {modal&&<Modal title={modal==='new'?'Novo agendamento':'Remarcar horário'} close={()=>setModal(null)}><BookingForm tenant={tenant} {...catalog} existing={modal==='new'?undefined:modal} done={()=>{setModal(null);setNotice('Horário reservado com sucesso.');void load()}}/></Modal>}
 {pay&&<Modal title="Concluir e registrar pagamento" close={()=>setPay(null)}><p>{pay.customer_name} · {money(pay.price_cents)}</p><form onSubmit={e=>{e.preventDefault();void action(pay,'completed',String(new FormData(e.currentTarget).get('method')))}}><Field label="Forma de pagamento"><select name="method" required>{paymentMethods.map(m=><option key={m} value={m}>{{pix:'PIX',cash:'Dinheiro',debit:'Débito',credit:'Crédito',other:'Outro'}[m]}</option>)}</select></Field><button className="primary" disabled={!paymentMethods.length}>Concluir atendimento</button></form></Modal>}</>
}
export function PublicPage(){
 const {slug=''}=useParams(),session=useSession(),[data,setData]=useState<CatalogData|null>(null),[notice,setNotice]=useState(''),[ready,setReady]=useState(false),[params,setParams]=useSearchParams(),[book,setBook]=useState(false)
 useEffect(()=>{rpc<CatalogData|null>('public_catalog',{shop_slug:slug}).then(d=>{setData(d);if(d)document.documentElement.dataset.theme=String(d.shop.theme)}).catch(e=>setNotice(message(e))).finally(()=>setReady(true))},[slug])
 if(!ready)return <main className="public-page"><Loading/></main>
 if(!data)return <main className="public-page"><h1>Barbearia indisponível</h1><p>A página ainda não foi publicada ou está temporariamente indisponível.</p><Notice text={notice}/><Link to="/app">Meu painel</Link></main>
 return <main className="public-page" style={{'--accent':String(data.shop.primary_color)} as React.CSSProperties}><nav className="public-nav"><Link className="brand" to={`/b/${slug}`}>{data.shop.name}</Link><Link to="/cliente">Meus agendamentos</Link></nav><TenantImage bucket="covers" path={data.shop.cover_path} alt="Ambiente da barbearia" className="public-cover"/><section className="public-hero"><p className="eyebrow">SEU ESTILO. SEU MOMENTO.</p><TenantImage bucket="logos" path={data.shop.logo_path} alt={String(data.shop.name)} className="public-logo"/><h1>{data.shop.name}</h1><p>{data.shop.description||data.shop.welcome_message}</p><button className="primary" onClick={()=>setBook(true)}>Agendar horário →</button><p>{data.shop.address} {data.shop.city}</p></section><Notice text={notice}/><h2>Nossos serviços</h2><div className="record-grid">{data.services.map(s=><article className="record" key={String(s.id)}><TenantImage bucket="service-images" path={s.image_path} alt={String(s.name)}/><h3>{s.name}</h3><p>{s.description}</p><strong>{money(Number(s.price_cents))}</strong><small>{s.duration_minutes} minutos</small><button onClick={()=>{setParams({agendar:'1',servico:String(s.id)});setBook(true)}}>Agendar</button></article>)}</div><h2>Quem cuida do seu estilo</h2><div className="record-grid">{data.professionals.map(p=><article className="record" key={String(p.id)}><div className="avatar">{String(p.name).slice(0,2)}</div><TenantImage bucket="professionals" path={p.photo_path} alt={String(p.name)}/><h3>{p.name}</h3><p>{p.specialties}</p></article>)}</div><footer><p>{data.shop.phone}</p>{data.shop.whatsapp&&<a href={`https://wa.me/${String(data.shop.whatsapp).replace(/\D/g,'')}`} target="_blank" rel="noreferrer">WhatsApp</a>}{data.shop.maps_url&&<a href={String(data.shop.maps_url)} target="_blank" rel="noreferrer">Como chegar</a>}</footer>
 {(book||params.get('agendar'))&&<Modal title="Reserve seu horário" close={()=>{setBook(false);setParams({},{replace:true})}}>{session.session?<BookingForm key={params.get('servico')??'default'} initialService={data.services.some(s=>s.id===params.get('servico'))?params.get('servico')!:undefined} tenant={String(data.shop.id)} services={data.services} professionals={data.professionals} done={()=>{setBook(false);setParams({},{replace:true});setNotice('Agendamento confirmado! Acompanhe em Meus agendamentos.')}}/>:<><p>Entre ou crie uma conta para reservar e acompanhar seus horários.</p><Link className="primary" to={`/login?next=${encodeURIComponent(`/b/${slug}?agendar=1${params.get('servico')?'&servico='+encodeURIComponent(params.get('servico')!):''}`)}`}>Entrar para agendar</Link><Link to={`/cadastro?next=${encodeURIComponent(`/b/${slug}?agendar=1`)}`}>Criar conta</Link></>}</Modal>}</main>
}
export function CustomerArea(){
 const [rows,setRows]=useState<Appointment[]>([]),[notice,setNotice]=useState(''),[edit,setEdit]=useState<Appointment|null>(null),[catalog,setCatalog]=useState<CatalogData|null>(null)
 const load=async()=>{try{const start=new Date();start.setMonth(start.getMonth()-6);const end=new Date();end.setMonth(end.getMonth()+6);setRows(await rpc('agenda',{tenant:null,from_date:start.toISOString(),until_date:end.toISOString()}))}catch(e){setNotice(message(e))}}
 useEffect(()=>{void load()},[])
 return <><Header title="Meus agendamentos" subtitle="Seus próximos horários e histórico."/><Notice text={notice}/>{!rows.length?<Empty text="Você ainda não tem agendamentos neste período."/>:rows.map(a=><article className="appointment" key={a.id}><div><h3>{a.shop_name}</h3><p>{dateTime(a.starts_at)} · {a.service_name} · {a.professional_name}</p><span className="badge">{labels[a.status]}</span></div>{['scheduled','confirmed'].includes(a.status)&&<div className="actions"><button onClick={async()=>{try{setCatalog(await rpc('public_catalog',{shop_slug:a.slug}));setEdit(a)}catch(e){setNotice(message(e))}}}>Remarcar</button><button onClick={async()=>{if(!confirm('Cancelar este horário?'))return;try{await rpc('appointment_action',{appointment:a.id,new_status:'cancelled'});await load()}catch(e){setNotice(message(e))}}}>Cancelar</button></div>}</article>)}{edit&&catalog&&<Modal title="Remarcar" close={()=>setEdit(null)}><BookingForm tenant={edit.barbershop_id} existing={edit} {...catalog} done={()=>{setEdit(null);void load()}}/></Modal>}</>
}
