import { useEffect,useState,type FormEvent } from 'react'
import { useParams } from 'react-router-dom'
import { records,message,type Row,type Entity,rpc,money,dateTime } from '../lib/api'
import { getSupabase } from '../lib/supabase'
import { TenantImage } from '../components/TenantImage'
import { Empty,Field,Header,Loading,Modal,Notice } from '../components/ui'
type Column={key:string;label:string;type?:string;required?:boolean;options?:[string,string][]}
const schemas:Record<string,{title:string;table:Entity;fields:Column[]}>= {
 servicos:{title:'Serviços',table:'services',fields:[{key:'name',label:'Nome',required:true},{key:'description',label:'Descrição'},{key:'price_cents',label:'Preço (R$)',type:'number',required:true},{key:'duration_minutes',label:'Duração (min)',type:'number',required:true},{key:'category',label:'Categoria'},{key:'is_active',label:'Ativo',type:'checkbox'}]},
 equipe:{title:'Equipe',table:'professionals',fields:[{key:'name',label:'Nome',required:true},{key:'phone',label:'Telefone'},{key:'email',label:'E-mail',type:'email'},{key:'specialties',label:'Especialidades'},{key:'commission_percent',label:'Comissão (%)',type:'number'},{key:'buffer_minutes',label:'Intervalo entre clientes (min)',type:'number'},{key:'status',label:'Status',options:[['available','Disponível'],['vacation','Férias'],['absent','Ausente'],['disabled','Desativado']]}]},
 clientes:{title:'Clientes',table:'customers',fields:[{key:'name',label:'Nome',required:true},{key:'phone',label:'Telefone',required:true},{key:'email',label:'E-mail',type:'email'}]},
 }
export function Catalog(){
 const [selectedServices,setSelectedServices]=useState<string[]>([]),[members,setMembers]=useState<Row[]>([]),[history,setHistory]=useState<{customer:Row;appointments:Row[];notes:Row[]}|null>(null)
 const {tenant='',module='servicos'}=useParams(),schema=schemas[module]??schemas.servicos!
 const [rows,setRows]=useState<Row[]>([]),[edit,setEdit]=useState<Row|null>(null),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[services,setServices]=useState<Row[]>([])
 async function load(){try{setRows(module==='clientes'?await rpc<Row[]>('customer_summary',{tenant}):await records(schema.table,tenant));if(module==='equipe'){setServices(await records('services',tenant));setMembers(await rpc<Row[]>('team_members',{tenant}))}}catch(e){setNotice(message(e))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[tenant,module]) // eslint-disable-line react-hooks/exhaustive-deps
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const body:Record<string,unknown>={}
  schema.fields.forEach(c=>{body[c.key]=c.type==='checkbox'?f.has(c.key):c.type==='number'?(c.key==='price_cents'?Math.round(Number(f.get(c.key))*100):Number(f.get(c.key))):String(f.get(c.key)??'')})
  try{const result=await records(schema.table,tenant,edit?.id?'PATCH':'POST',edit?.id?body:{...body,barbershop_id:tenant},edit?.id?String(edit.id):undefined)
   const savedId=String(result[0]?.id??edit?.id)
   setEdit(previous=>({...previous,id:savedId}))
   if(module==='equipe'){const ids=f.getAll('services').map(String);await rpc('set_professional_services',{tenant,professional:savedId,service_ids:ids});await records('professionals',tenant,'PATCH',{member_id:f.get('member_id')||null},savedId)}
   const photo=f.get('photo');if(photo instanceof File&&photo.size){const bucket=module==='equipe'?'professionals':'service-images',path=`${tenant}/${crypto.randomUUID()}.${photo.name.split('.').pop()}`;const {error}=await getSupabase().storage.from(bucket).upload(path,photo);if(error)throw error;await records(schema.table,tenant,'PATCH',{[module==='equipe'?'photo_path':'image_path']:path},savedId)}
   setEdit(null);setNotice('Salvo com sucesso.');await load()
  }catch(e){setNotice(message(e))}finally{setBusy(false)}
 }
 async function remove(row:Row){if(!confirm(`Excluir ${row.name}? Registros com histórico serão preservados.`))return;try{await records(schema.table,tenant,'DELETE',undefined,String(row.id));await load()}catch(e){setNotice(message(e))}}
 const filtered=rows.filter(r=>`${r.name} ${r.phone??''}`.toLowerCase().includes(search.toLowerCase()))
 return <><Header title={schema.title} subtitle={`${rows.length} registros na sua barbearia`}><button className="primary" onClick={()=>{setSelectedServices([]);setEdit({is_active:true,status:'available',commission_percent:0,buffer_minutes:0})}}>+ Adicionar</button></Header><Notice text={notice}/><input className="search" placeholder="Buscar por nome ou telefone…" value={search} onChange={e=>setSearch(e.target.value)} aria-label="Buscar"/>
 {loading?<Loading/>:!filtered.length?<Empty/>:<div className="record-grid">{filtered.map(row=><article className="record" key={String(row.id)}><div className="avatar">{String(row.name).slice(0,2).toUpperCase()}</div><TenantImage bucket={module==='equipe'?'professionals':'service-images'} path={module==='equipe'?row.photo_path:row.image_path} alt={String(row.name)}/><h3>{row.name}</h3><p>{row.description||row.specialties||row.phone||'—'}</p>{module==='servicos'&&<strong>{money(Number(row.price_cents))} <small>· {row.duration_minutes} min</small></strong>}<span className="badge">{module==='servicos'?(row.is_active?'Ativo':'Desativado'):module==='equipe'?String(row.status):String(row.email||'Cliente')}</span><div className="actions">{module==='clientes'&&<><small>{row.visits} visitas · {money(Number(row.spent_cents))}</small><button onClick={async()=>{try{const h=await rpc<{appointments:Row[];notes:Row[]}>('customer_history',{tenant,customer:row.id});setHistory({customer:row,...h})}catch(e){setNotice(message(e))}}}>Histórico</button></>}<button onClick={async()=>{try{if(module==='equipe')setSelectedServices(await rpc<string[]>('professional_service_ids',{tenant,professional:row.id}));setEdit(row)}catch(e){setNotice(message(e))}}}>Editar</button><button className="quiet" onClick={()=>void remove(row)}>Excluir</button></div></article>)}</div>}
 {edit&&<Modal title={edit.id?'Editar cadastro':'Novo cadastro'} close={()=>setEdit(null)}><form onSubmit={save} className="form-grid">{schema.fields.map(c=><Field key={c.key} label={c.label}>{c.options?<select name={c.key} defaultValue={String(edit[c.key]??c.options[0]?.[0])}>{c.options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>:<input name={c.key} type={c.type??'text'} required={c.required} min={c.key==='duration_minutes'?5:0} step={c.key==='commission_percent'||c.key==='price_cents'?'.01':'1'} max={c.key==='commission_percent'?100:undefined} defaultChecked={c.type==='checkbox'?Boolean(edit[c.key]):undefined} defaultValue={c.type==='checkbox'?undefined:String(c.key==='price_cents'&&edit[c.key]!=null?Number(edit[c.key])/100:edit[c.key]??'')}/>}</Field>)}
 {module==='equipe'&&<fieldset className="full"><legend>Habilitar serviços (vínculos históricos são preservados)</legend>{services.map(s=><label className="check" key={String(s.id)}><input type="checkbox" name="services" value={String(s.id)} defaultChecked={selectedServices.includes(String(s.id))}/>{s.name}</label>)}</fieldset>}
 <>{module!=='clientes'&&<Field label="Foto"><input name="photo" type="file" accept="image/png,image/jpeg,image/webp"/></Field>}{module==='equipe'&&<Field label="Usuário vinculado"><select name="member_id" defaultValue={String(edit.member_id??'')}><option value="">Sem acesso individual</option>{members.filter(m=>m.role==='professional').map(m=><option key={String(m.id)} value={String(m.id)}>{m.name||m.email}</option>)}</select></Field>}</><Notice text={notice}/><button disabled={busy} className="primary full">{busy?'Salvando…':'Salvar'}</button></form></Modal>}{history&&<Modal title={String(history.customer.name)} close={()=>setHistory(null)}>{history.appointments.map(a=><p key={String(a.id)}>{dateTime(String(a.starts_at))} · {a.service} · {a.status} · {money(Number(a.price_cents))}</p>)}<h3>Observações internas</h3>{history.notes.map(n=><p key={String(n.id)}>{n.body}</p>)}<form onSubmit={async e=>{e.preventDefault();const body=String(new FormData(e.currentTarget).get('body'));try{await records('customer_notes',tenant,'POST',{barbershop_id:tenant,customer_id:history.customer.id,body});const h=await rpc<{appointments:Row[];notes:Row[]}>('customer_history',{tenant,customer:history.customer.id});setHistory({...history,...h})}catch(e){setNotice(message(e))}}}><Field label="Nova observação"><textarea name="body" required/></Field><button className="primary">Adicionar observação</button></form></Modal>}</>
}
