import { useEffect,useState,type FormEvent } from 'react'
import { Link,useParams } from 'react-router-dom'
import { records,message,rpc,type Row } from '../lib/api'
import { Field,Header,Notice,Loading } from '../components/ui'
import { themes } from '../config/themes'
import { getSupabase } from '../lib/supabase'
import type { Theme } from '../types/domain'
export function Settings(){
 const [plan,setPlan]=useState<Row|null>(null)
 const {tenant=''}=useParams();const [tab,setTab]=useState('Minha barbearia'),[shop,setShop]=useState<Row|null>(null),[settings,setSettings]=useState<Row|null>(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState<Theme|null>(null)
 useEffect(()=>{Promise.all([records('barbershops',tenant),records('settings',tenant)]).then(([b,s])=>{setShop(b[0]??null);setSettings(s[0]??null);void rpc<Row>('plan_details',{tenant}).then(setPlan).catch(()=>{})}).catch(e=>setNotice(message(e)))},[tenant])
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget),body:Record<string,unknown>={};f.forEach((v,k)=>{body[k]=v})
  if(tab==='Agendamento'){body.accepted_payments=f.getAll('payments');['cancellation_hours','booking_notice_minutes','booking_horizon_days','slot_minutes'].forEach(k=>body[k]=Number(f.get(k)));['commissions_enabled','reminder_24h','reminder_2h'].forEach(k=>body[k]=f.has(k))}
  if(tab==='Minha barbearia')body.is_published=f.has('is_published')
  try{if(tab==='Usuários'){await rpc('manage_member',{tenant,member_email:f.get('email'),member_role:f.get('role'),enabled:f.has('enabled')})}
   else{const result=await records(tab==='Agendamento'?'settings':'barbershops',tenant,'PATCH',body);if(tab==='Agendamento')setSettings(result[0]??null);else setShop(result[0]??null)}setNotice('Configurações salvas.')
  }catch(e){setNotice(message(e))}finally{setBusy(false)}
 }
 async function upload(file:File|undefined,bucket:'logos'|'covers'){
  if(!file)return;setBusy(true);try{const path=`${tenant}/${crypto.randomUUID()}.${file.name.split('.').pop()}`
   const {error}=await getSupabase().storage.from(bucket).upload(path,file);if(error)throw error
   const result=await records('barbershops',tenant,'PATCH',{[bucket==='logos'?'logo_path':'cover_path']:path});setShop(result[0]??null);setNotice('Imagem enviada.')
  }catch{setNotice('Não foi possível enviar. Use JPG, PNG ou WebP, até 5 MB para logo e 10 MB para capa.')}finally{setBusy(false)}
 }
 return <><Header title="Configurações" subtitle="Tudo com a identidade da sua barbearia."/><div className="tabs">{['Minha barbearia','Aparência','Agendamento','Usuários','Plano'].map(t=><button key={t} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{t}</button>)}<Link to={`/app/${tenant}/horarios`}>Horários</Link><Link to={`/app/${tenant}/whatsapp`}>WhatsApp</Link></div><Notice text={notice}/>{!shop?<Loading/>:tab==='Aparência'?<section><div className="theme-options">{Object.entries(themes).map(([key,t])=><button className={`theme-preview ${key} ${preview===key?'chosen':''}`} key={key} onClick={()=>setPreview(key as Theme)}><span>{t.label}</span><div className="preview-lines"><i/><i/><i/></div><p>{t.description}</p></button>)}</div>{preview&&<div className="actions"><button className="primary" onClick={async()=>{try{await records('barbershops',tenant,'PATCH',{theme:preview});document.documentElement.dataset.theme=preview;setNotice('Tema aplicado.')}catch(e){setNotice(message(e))}}}>Aplicar {themes[preview].label}</button><button onClick={()=>setPreview(null)}>Cancelar prévia</button></div>}</section>:tab==='Plano'?<div className="panel"><h2>{plan?.plan??'Carregando plano…'}</h2><p>Status: {plan?.status}</p><p>{plan?.professionals} profissionais ativos / {plan?.professional_limit??'ilimitado'}</p><p>Para alterar o plano, entre em contato com a administração da plataforma.</p></div>:<form className="panel form-grid" onSubmit={save} key={tab}>
 {tab==='Minha barbearia'&&<>{[['name','Nome'],['description','Descrição'],['phone','Telefone'],['whatsapp','WhatsApp'],['instagram','Instagram'],['address','Endereço'],['postal_code','CEP'],['city','Cidade'],['state','Estado'],['maps_url','Google Maps (https://)'],['welcome_message','Apresentação']].map(([key,label])=><Field label={label!} key={key}><input name={key} defaultValue={String(shop[key!]??'')} required={key==='name'}/></Field>)}<Field label="Cor principal"><input type="color" name="primary_color" defaultValue={String(shop.primary_color)}/></Field><Field label="Cor secundária"><input type="color" name="secondary_color" defaultValue={String(shop.secondary_color)}/></Field><Field label="Logo"><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>void upload(e.target.files?.[0],'logos')}/></Field><Field label="Capa"><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>void upload(e.target.files?.[0],'covers')}/></Field><label className="check"><input name="is_published" type="checkbox" defaultChecked={Boolean(shop.is_published)}/>Publicar página e permitir reservas</label><Link to={`/b/${shop.slug}`}>Abrir página pública ↗</Link></>}
 {tab==='Agendamento'&&settings&&<>{[['cancellation_hours','Cancelamento: antecedência em horas'],['booking_notice_minutes','Reserva: antecedência em minutos'],['booking_horizon_days','Reservar até quantos dias'],['slot_minutes','Intervalo da grade em minutos']].map(([k,l])=><Field key={k} label={l!}><input type="number" min={k==='cancellation_hours'||k==='booking_notice_minutes'?0:1} name={k} required defaultValue={Number(settings[k!])}/></Field>)}<fieldset className="full"><legend>Formas de pagamento aceitas</legend>{[['pix','PIX'],['cash','Dinheiro'],['debit','Débito'],['credit','Crédito'],['other','Outro']].map(([v,l])=><label className="check" key={v}><input name="payments" type="checkbox" value={v} defaultChecked={Array.isArray(settings.accepted_payments)&&settings.accepted_payments.includes(v)}/>{l}</label>)}</fieldset>{[['commissions_enabled','Exibir comissões'],['reminder_24h','Lembrete 24 horas antes'],['reminder_2h','Lembrete 2 horas antes']].map(([k,l])=><label className="check" key={k}><input name={k} type="checkbox" defaultChecked={Boolean(settings[k!])}/>{l}</label>)}</>}
 {tab==='Usuários'&&<><p className="full">O usuário deve criar e confirmar sua conta antes de ser vinculado. Você pode desativar um vínculo desmarcando “Acesso ativo”.</p><Field label="E-mail do usuário"><input type="email" name="email" required/></Field><Field label="Função"><select name="role"><option value="manager">Gerente</option><option value="receptionist">Recepção</option><option value="professional">Profissional</option></select></Field><label className="check"><input type="checkbox" name="enabled" defaultChecked/>Acesso ativo</label></>}
 <button className="primary full" disabled={busy}>{busy?'Salvando…':'Salvar configurações'}</button></form>}</>
}
export function Hours(){
 const {tenant=''}=useParams(),[professionals,setProfessionals]=useState<Row[]>([]),[selected,setSelected]=useState(''),[rows,setRows]=useState<Row[]>([]),[notice,setNotice]=useState('')
 const days=['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado']
 const load=async()=>{try{setRows((await records(selected?'professional_schedules':'business_hours',tenant)).filter(r=>!selected||r.professional_id===selected))}catch(e){setNotice(message(e))}}
 useEffect(()=>{records('professionals',tenant).then(setProfessionals).catch(e=>setNotice(message(e)))},[tenant])
 useEffect(()=>{void load()},[selected,tenant]) // eslint-disable-line react-hooks/exhaustive-deps
 const minute=(value:string)=>{const [h,m]=value.split(':').map(Number);return h!*60+m!}
 const time=(v:number)=>`${String(Math.floor(v/60)).padStart(2,'0')}:${String(v%60).padStart(2,'0')}`
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await records(selected?'professional_schedules':'business_hours',tenant,'POST',{barbershop_id:tenant,...(selected?{professional_id:selected}:{}),weekday:Number(f.get('day')),start_minute:minute(String(f.get('start'))),end_minute:minute(String(f.get('end')))});setNotice('Período adicionado.');await load()}catch(e){setNotice(message(e))}}
 return <><Header title="Horários" subtitle="Adicione períodos separados para reservar o intervalo de almoço."/><Notice text={notice}/><Field label="Agenda"><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Funcionamento da barbearia</option>{professionals.map(p=><option key={String(p.id)} value={String(p.id)}>{p.name}</option>)}</select></Field><form onSubmit={add} className="panel form-grid"><Field label="Dia"><select name="day">{days.map((d,i)=><option value={i} key={d}>{d}</option>)}</select></Field><Field label="Início"><input type="time" name="start" required defaultValue="09:00"/></Field><Field label="Fim"><input type="time" name="end" required defaultValue="12:00"/></Field><button className="primary">Adicionar período</button></form><div className="panel">{rows.map(r=><div className="list-row" key={String(r.id)}><strong>{days[Number(r.weekday)]}</strong><span>{time(Number(r.start_minute))} — {time(Number(r.end_minute))}</span><button onClick={async()=>{try{await records(selected?'professional_schedules':'business_hours',tenant,'DELETE',undefined,String(r.id));await load()}catch(e){setNotice(message(e))}}}>Remover</button></div>)}</div></>
}
