import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { chromium,expect } from '@playwright/test'
const credentials=JSON.parse(await readFile(new URL('../demo-credentials.local',import.meta.url),'utf8'))
const browser=await chromium.launch({channel:'msedge',headless:true})
const page=await browser.newPage({viewport:{width:1440,height:1000}})
const errors=[]
page.on('pageerror',error=>errors.push(error.message))
try{
 await page.goto('http://127.0.0.1:5173/login')
 await page.getByLabel('E-mail',{exact:true}).fill(credentials.email)
 await page.getByLabel('Senha',{exact:true}).fill(credentials.password)
 await page.getByRole('button',{name:'Entrar',exact:true}).click()
 await page.waitForURL('**/admin',{timeout:30000})
 await page.getByRole('heading',{name:'Plataforma',exact:true}).waitFor()
 await page.goto(`http://127.0.0.1:5173/app/${credentials.demo_tenant}/agenda`)
 await page.getByRole('heading',{name:'Agenda',exact:true}).waitFor()
 await page.getByRole('button',{name:'+ Novo agendamento',exact:true}).click()
 await page.getByRole('dialog').waitFor()
 await expect.poll(()=>page.getByLabel('1. Serviço').locator('option').count()).toBeGreaterThan(1)
 await page.getByRole('button',{name:'Fechar',exact:true}).click()
 await page.goto(`http://127.0.0.1:5173/app/${credentials.demo_tenant}/servicos`)
 await page.getByRole('heading',{name:'Serviços',exact:true}).waitFor()
 await page.getByRole('heading',{name:'Corte',exact:true}).waitFor()
 await page.goto(`http://127.0.0.1:5173/app/${credentials.demo_tenant}/configuracoes`)
 await page.getByRole('button',{name:'Aparência',exact:true}).click()
 await page.getByRole('button',{name:/Classic Barber/}).click()
 await page.getByRole('button',{name:'Aplicar Classic Barber',exact:true}).waitFor()
 await page.getByRole('button',{name:'Cancelar prévia',exact:true}).click()
 await page.setViewportSize({width:390,height:844})
 await page.goto(`http://127.0.0.1:5173/b/${credentials.demo_slug}`)
 await page.getByRole('heading',{name:'Barbearia Prime Demo',exact:true}).waitFor()
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+1)
 assert.equal(overflow,false,'Página pública não deve ter rolagem horizontal no celular')
 await page.getByRole('button',{name:'Agendar horário →',exact:true}).click()
 await page.getByRole('dialog').waitFor()
 await page.getByRole('button',{name:'Fechar',exact:true}).click()
 await page.goto(`http://127.0.0.1:5173/b/${credentials.demo_slug}?agendar=1`)
 await page.getByRole('dialog').waitFor()
 await page.getByRole('button',{name:'Fechar',exact:true}).click()
 await expect(page.getByRole('dialog')).toHaveCount(0)
 await page.locator('article.record').filter({has:page.getByRole('heading',{name:'Barba',exact:true})}).getByRole('button',{name:'Agendar',exact:true}).click()
 await expect(page.getByLabel('1. Serviço').locator('option:checked')).toContainText('Barba')
 await page.getByRole('button',{name:'Fechar',exact:true}).click()
 await page.goto('http://127.0.0.1:5173/perfil')
 await page.getByRole('heading',{name:'Meu perfil',exact:true}).waitFor()
 await page.reload()
 await page.getByRole('heading',{name:'Meu perfil',exact:true}).waitFor()
 await page.getByRole('button',{name:'Abrir menu',exact:true}).click()
 await page.getByRole('button',{name:'Sair da conta',exact:true}).click()
 await page.waitForURL('**/login?next=*')
 await page.goto('http://127.0.0.1:5173/admin')
 await page.waitForURL('**/login?next=*')
 await page.waitForTimeout(500)
 await expect(page.getByRole('heading',{name:'Bem-vindo de volta.',exact:true})).toBeVisible()
 assert.deepEqual(errors,[])
 process.stdout.write('Navegador: login, Super Admin, agenda, formulário de reserva, serviços, prévia de tema e página pública mobile: OK.\n')
}finally{await browser.close()}
